// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: gfunc/gfunc.proto

package gfunc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GfuncMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Funcs []*GfuncFuncOptions `protobuf:"bytes,1,rep,name=funcs,proto3" json:"funcs,omitempty"`
}

func (x *GfuncMessageOptions) Reset() {
	*x = GfuncMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gfunc_gfunc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GfuncMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GfuncMessageOptions) ProtoMessage() {}

func (x *GfuncMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gfunc_gfunc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GfuncMessageOptions.ProtoReflect.Descriptor instead.
func (*GfuncMessageOptions) Descriptor() ([]byte, []int) {
	return file_gfunc_gfunc_proto_rawDescGZIP(), []int{0}
}

func (x *GfuncMessageOptions) GetFuncs() []*GfuncFuncOptions {
	if x != nil {
		return x.Funcs
	}
	return nil
}

type GfuncFuncOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Template string            `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Values   map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GfuncFuncOptions) Reset() {
	*x = GfuncFuncOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gfunc_gfunc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GfuncFuncOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GfuncFuncOptions) ProtoMessage() {}

func (x *GfuncFuncOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gfunc_gfunc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GfuncFuncOptions.ProtoReflect.Descriptor instead.
func (*GfuncFuncOptions) Descriptor() ([]byte, []int) {
	return file_gfunc_gfunc_proto_rawDescGZIP(), []int{1}
}

func (x *GfuncFuncOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GfuncFuncOptions) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *GfuncFuncOptions) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var file_gfunc_gfunc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*GfuncMessageOptions)(nil),
		Field:         53000,
		Name:          "gfunc.gfunc",
		Tag:           "bytes,53000,opt,name=gfunc",
		Filename:      "gfunc/gfunc.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// ormable will cause orm code to be generated for this message/object
	//
	// optional gfunc.GfuncMessageOptions gfunc = 53000;
	E_Gfunc = &file_gfunc_gfunc_proto_extTypes[0]
)

var File_gfunc_gfunc_proto protoreflect.FileDescriptor

var file_gfunc_gfunc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x2f, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x13,
	0x47, 0x66, 0x75, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x66, 0x75, 0x6e, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x2e, 0x47, 0x66, 0x75, 0x6e, 0x63,
	0x46, 0x75, 0x6e, 0x63, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x75, 0x6e,
	0x63, 0x73, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x47, 0x66, 0x75, 0x6e, 0x63, 0x46, 0x75, 0x6e, 0x63,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x2e,
	0x47, 0x66, 0x75, 0x6e, 0x63, 0x46, 0x75, 0x6e, 0x63, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x3a,
	0x53, 0x0a, 0x05, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x9e, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x2e, 0x47, 0x66, 0x75, 0x6e, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x67,
	0x66, 0x75, 0x6e, 0x63, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x75, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x74, 0x2d, 0x64, 0x65, 0x76, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x66, 0x75, 0x6e, 0x63,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x67, 0x66, 0x75, 0x6e, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gfunc_gfunc_proto_rawDescOnce sync.Once
	file_gfunc_gfunc_proto_rawDescData = file_gfunc_gfunc_proto_rawDesc
)

func file_gfunc_gfunc_proto_rawDescGZIP() []byte {
	file_gfunc_gfunc_proto_rawDescOnce.Do(func() {
		file_gfunc_gfunc_proto_rawDescData = protoimpl.X.CompressGZIP(file_gfunc_gfunc_proto_rawDescData)
	})
	return file_gfunc_gfunc_proto_rawDescData
}

var file_gfunc_gfunc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gfunc_gfunc_proto_goTypes = []interface{}{
	(*GfuncMessageOptions)(nil),         // 0: gfunc.GfuncMessageOptions
	(*GfuncFuncOptions)(nil),            // 1: gfunc.GfuncFuncOptions
	nil,                                 // 2: gfunc.GfuncFuncOptions.ValuesEntry
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
}
var file_gfunc_gfunc_proto_depIdxs = []int32{
	1, // 0: gfunc.GfuncMessageOptions.funcs:type_name -> gfunc.GfuncFuncOptions
	2, // 1: gfunc.GfuncFuncOptions.values:type_name -> gfunc.GfuncFuncOptions.ValuesEntry
	3, // 2: gfunc.gfunc:extendee -> google.protobuf.MessageOptions
	0, // 3: gfunc.gfunc:type_name -> gfunc.GfuncMessageOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gfunc_gfunc_proto_init() }
func file_gfunc_gfunc_proto_init() {
	if File_gfunc_gfunc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gfunc_gfunc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GfuncMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gfunc_gfunc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GfuncFuncOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gfunc_gfunc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_gfunc_gfunc_proto_goTypes,
		DependencyIndexes: file_gfunc_gfunc_proto_depIdxs,
		MessageInfos:      file_gfunc_gfunc_proto_msgTypes,
		ExtensionInfos:    file_gfunc_gfunc_proto_extTypes,
	}.Build()
	File_gfunc_gfunc_proto = out.File
	file_gfunc_gfunc_proto_rawDesc = nil
	file_gfunc_gfunc_proto_goTypes = nil
	file_gfunc_gfunc_proto_depIdxs = nil
}
